[project]
name = "cliplens"
version = "0.1.0"
description = "Local AI-powered image browser and manager based on Chinese-CLIP"
readme = "README.md"
requires-python = ">=3.10"
package = false

dependencies = [
    "pyside6>=6.6",
    "pillow>=10.0",
    "lancedb>=0.4",
    "send2trash>=1.8",
    "onnxruntime>=1.16",
    "psutil>=5.9",
    "setuptools",
    "torch",
    "torchvision",
    "cn-clip>=1.5.0",
]

[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv]
override-dependencies = [
    "lmdb>=1.4.1",
]